# Logging level
log_level: DEBUG  # Can be DEBUG, INFO, WARNING, ERROR, or CRITICAL

# Sync timing settings
sync_delay: 5s    # Delay before processing a webhook (e.g., 5s, 10s, 1m)
sync_interval: 2s  # Time between individual sync operations (e.g., 2s, 500ms, 1m)

# Define supported event types
webhook_events:
  sonarr:
    - "Grab"
    - "Download"
    - "Rename"
    - "SeriesDelete"
    - "SeriesAdd"
    - "EpisodeFileDelete"
    - "Import"
  radarr:
    - "Grab"
    - "Download"
    - "Rename"
    - "MovieDelete"
    - "MovieFileDelete"
    - "Import"

# Media server configurations for scanning
# You can add multiple media servers of the same type
media_servers:
  - name: "plex"
    type: "plex"
    url: "http://plex:32400"
    token: "api_key"
    enabled: true
    # Optional: Rewrite rules for media server
    #rewrite:
    #  - from_path: /mnt/plex
    #    to_path: /mnt/remote/plex

  - name: "jellyfin"
    type: "jellyfin"
    url: "http://jellyfin:8096"
    api_key: "api_key"
    enabled: true
    
  - name: "emby"
    type: "emby"
    url: "http://emby:8096"
    api_key: "api_key"
    enabled: true

instances:
  - name: "sonarr4k"
    type: "sonarr"
    url: "http://sonarr4k:8989"
    api_key: "api_key"
    root_folder_path: "/mnt/plex/TV - 4K"
    season_folder: false
    quality_profile_id: 8
    language_profile_id: 1
    search_on_sync: false
    enabled_events:
      - "Import"

  - name: "sonarrmux"
    type: "sonarr"
    url: "http://sonarrmux:8989"
    api_key: "api_key"
    root_folder_path: "/mnt/plex/TV - Remux"
    season_folder: true
    quality_profile_id: 5
    language_profile_id: 1
    search_on_sync: false
    enabled_events:
      - "Import"

  - name: "radarr4k"
    type: "radarr"
    url: "http://radarr4k:7879"
    api_key: "api_key"
    root_folder_path: "/mnt/plex/Movies - 4K"
    quality_profile_id: 8
    search_on_sync: false
    enabled_events:
      - "Import"

  - name: "radarrmux"
    type: "radarr"
    url: "http://radarrMux:7878"
    api_key: "api_key"
    root_folder_path: "/mnt/plex/Movies - Remux"
    quality_profile_id: 10
    search_on_sync: false
    enabled_events:
      - "Import"
    # Optional: Rewrite rules for instance
    #rewrite:
    #  - from_path: "/mnt/plex/Movies - Remux"
    #    to_path: "/mnt/remote/plex/Movies - Remux"