services:
  autosync:
    image: ghcr.io/pukabyte/autosync:latest
    container_name: autosync
    hostname: autosync
    user: 1000:1000
    ports:
      - 3536:3536
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped